apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml   # uncomment if you want ingress
images:
  - name: docker.io/bhaskar2001/gitops-demo
    newTag: v1
